spring:
  config:
    activate:
      on-profile: local-mssql

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${SPRING_DATA_SOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # 운영 환경에서는 적절히 update, validate 등으로 변경 필요
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect # MSSQL용 Hibernate Dialect 사용
    defer-datasource-initialization: true # 초기 데이터 로딩 시점을 지연

  sql:
    init:
      mode: never
      encoding: UTF-8
      data-locations: >
        classpath:/data/init.sql
      # classpath:/data/order_scenario.sql
      continue-on-error: false

  redission:
    address: redis://localhost:6379