server:
  port: 9001

spring:
  application:
    name: order-service
  profiles:
    active: dev

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

slack:
  webhook-uri:
  channel:

web-client:
  base-url: http://localhost:8000

application:
  kafka-property:
    bootstrap-servers: localhost:29092

    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer

    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumer-group-id-logic: consumer-group-logic # 비즈니스로직 컨슈머
    consumer-group-id-outbox: consumer-group-outbox # 아웃박스 컨슈머

  topic:
    order:
      order-created: order.order-created.dev # 주문생성 토픽
    product:
      inventory-deduct-failure: product.inventory-deduct-failure.dev # 재고 차감실패 토픽
    user:
      point-use: user.point-use.dev # 사용자 포인트 사용 토픽
